In [1]:
import numpy as np
import pandas as pd
data= np.load('galaxy_catalogue.npy')

In [2]:
df = pd.DataFrame(data)
df


u-g      g-r      r-i      i-z       ecc      m4_u      m4_g  \
0    1.85765  0.67158  0.42310  0.30610  0.585428  2.251946  2.339849   
1    1.74259  0.86085  0.44927  0.28851  0.749812  2.031566  2.084156   
2    2.10697  0.96710  0.56810  0.33747  0.630089  1.992887  2.450746   
3    1.22840  0.60446  0.39049  0.28913  0.668999  2.056115  2.182252   
4    1.80792  0.78124  0.45528  0.35067  0.500170  2.259167  2.194723   
..       ...      ...      ...      ...       ...       ...       ...   
775  1.34594  0.64285  0.37813  0.23107  0.779956  2.421518  2.248886   
776  1.19482  0.49611  0.31017  0.16244  0.722125  2.211442  2.294102   
777  1.21489  0.57253  0.35423  0.21312  0.793392  2.264709  2.319192   
778  1.41797  0.86460  0.40020  0.35307  0.835901  2.011354  2.023669   
779  1.49346  0.86623  0.43432  0.31509  0.490623  2.387251  2.529668   

         m4_r      m4_i      m4_z  petroR50_u  petroR50_r  petroR50_z  \
0    2.380652  2.359738  2.395528    3.095123    3.818919    3.826230   
1    2.092272  2.124075  2.133154    1.430436    1.422533    1.385727   
2    2.473116  2.465324  2.438683    3.099957    3.623704    3.463300   
3    2.309510  2.391414  2.472397    3.627267    4.063471    3.717708   
4    2.264567  2.334713  2.352568    3.256751    3.153533    2.254511   
..        ...       ...       ...         ...         ...         ...   
775  2.589488  2.615007  2.601444   13.877220   11.936910   11.337210   
776  2.327795  2.371559  2.358487    3.032364    3.348147    3.062732   
777  2.388157  2.392148  2.384103    4.652165    4.031008    3.122812   
778  2.326873  2.676343  2.560389    5.442954    4.227347    3.774427   
779  2.525753  2.490839  2.487824    5.082120    3.473336    3.107052   

     petroR90_u  petroR90_r  petroR90_z   class  
0      5.174814    8.263009   11.477340  merger  
1      3.732712    3.416921    3.330347  merger  
2      9.110857    8.354343   11.265390  merger  
3      9.580675   12.202420   11.826220  merger  
4      9.206746    9.790146    6.636931  merger  
..          ...         ...         ...     ...  
775   32.374710   25.266770   25.934250  spiral  
776    5.833694    8.061935    7.840197  spiral  
777    9.610085    9.280005    6.708179  spiral  
778   16.256520    7.738220    7.865478  spiral  
779    9.206557    8.380891    7.720072  spiral  

[780 rows x 17 columns]

In [3]:
df.shape

(780, 17)

In [4]:
X = df.iloc[:,:10]
#y= df.iloc[:,-1]
y=pd.DataFrame(df.iloc[:,-1])
y.shape

(780, 1)

In [5]:
X['conc_u']=(df['petroR50_u'])/(df['petroR90_u'])
X['conc_r']=df['petroR50_r']/df['petroR90_r']
X['conc_z']= df['petroR50_z']/df['petroR90_z']
X

u-g      g-r      r-i      i-z       ecc      m4_u      m4_g  \
0    1.85765  0.67158  0.42310  0.30610  0.585428  2.251946  2.339849   
1    1.74259  0.86085  0.44927  0.28851  0.749812  2.031566  2.084156   
2    2.10697  0.96710  0.56810  0.33747  0.630089  1.992887  2.450746   
3    1.22840  0.60446  0.39049  0.28913  0.668999  2.056115  2.182252   
4    1.80792  0.78124  0.45528  0.35067  0.500170  2.259167  2.194723   
..       ...      ...      ...      ...       ...       ...       ...   
775  1.34594  0.64285  0.37813  0.23107  0.779956  2.421518  2.248886   
776  1.19482  0.49611  0.31017  0.16244  0.722125  2.211442  2.294102   
777  1.21489  0.57253  0.35423  0.21312  0.793392  2.264709  2.319192   
778  1.41797  0.86460  0.40020  0.35307  0.835901  2.011354  2.023669   
779  1.49346  0.86623  0.43432  0.31509  0.490623  2.387251  2.529668   

         m4_r      m4_i      m4_z    conc_u    conc_r    conc_z  
0    2.380652  2.359738  2.395528  0.598113  0.462170  0.333373  
1    2.092272  2.124075  2.133154  0.383216  0.416320  0.416091  
2    2.473116  2.465324  2.438683  0.340249  0.433751  0.307428  
3    2.309510  2.391414  2.472397  0.378602  0.333005  0.314361  
4    2.264567  2.334713  2.352568  0.353735  0.322113  0.339692  
..        ...       ...       ...       ...       ...       ...  
775  2.589488  2.615007  2.601444  0.428644  0.472435  0.437152  
776  2.327795  2.371559  2.358487  0.519802  0.415303  0.390645  
777  2.388157  2.392148  2.384103  0.484092  0.434376  0.465523  
778  2.326873  2.676343  2.560389  0.334817  0.546294  0.479873  
779  2.525753  2.490839  2.487824  0.552011  0.414435  0.402464  

[780 rows x 13 columns]

In [20]:

from sklearn.preprocessing import OrdinalEncoder
ordinal_encoder = OrdinalEncoder()
y_encoded = ordinal_encoder.fit_transform(y)
y_encoded.shape

(780, 1)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [8]:
X

array([[ 0.32964523, -0.23879979,  0.34871761, ...,  1.40345495,
         0.94013513, -0.50659529],
       [ 0.16039081,  0.32826371,  0.6246533 , ..., -0.440167  ,
         0.38832996,  0.3576287 ],
       [ 0.69639747,  0.64659464,  1.87759326, ..., -0.80879085,
         0.59810803, -0.77765506],
       ...,
       [-0.61586121, -0.53555912, -0.3774456 , ...,  0.42525678,
         0.60562628,  0.87408587],
       [-0.31712848,  0.33949892,  0.1072607 , ..., -0.85539255,
         1.95256007,  1.02400641],
       [-0.20608193,  0.34438249,  0.46702095, ...,  1.00794097,
         0.36564463,  0.2152592 ]])

In [9]:
def hypothesis(theta, x):
    z = np.dot(x,theta)
    #print('z= ',z)
    return(1/(1+np.exp(-z)))
#correct now, dont change

In [10]:
def cost(h,y):
    m=len(y)
    return ((1/m)*(np.dot(-y.T,np.log(h))-np.dot((1-y).T,np.log(1-h))))

In [11]:
def gradient_descent(x,y,theta,alpha,loops):
    m=len(y)
    theta_matrix=np.zeros((14,0))
    for i in np.unique(y):
        y_multi= np.where(y==i,1,0)
        for loop in range(loops):
            h=hypothesis(theta,x)
            theta = theta - (alpha/m)*(np.dot(x.T,h-y_multi))
        theta_matrix=np.append(theta_matrix,theta,axis=1)
    return theta_matrix

In [12]:
def hypothesis_final(theta,x):
    z0=np.dot(x,theta[:,0])
    z1=np.dot(x,theta[:,1])
    z2=np.dot(x,theta[:,2])
    return(1/(1+np.exp(-z0)),1/(1+np.exp(-z1)),1/(1+np.exp(-z2)))

In [13]:
def fit(x,y,alpha,loops):
    theta=np.zeros((14,1))
    theta_min=gradient_descent(x,y,theta,alpha,loops)
    h0,h1,h2=hypothesis_final(theta_min,x)
    h0=h0.reshape(x.shape[0],1)
    h1=h1.reshape(x.shape[0],1)
    h2=h2.reshape(x.shape[0],1)
    H_final=np.zeros((x.shape[0],0))
    H_final=np.append(H_final,h0,axis=1)
    H_final=np.append(H_final,h1,axis=1)
    H_final=np.append(H_final,h2,axis=1)
    h_max = np.amax(H_final, axis=1,keepdims = True)
    index = np.where(H_final == h_max)
    prediction = index[1]
    prediction = prediction.reshape(x.shape[0],1)
    return prediction

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded)
X_train = np.c_[np.ones(len(X_train),dtype='int64'),X_train]
X_test = np.c_[np.ones(len(X_test),dtype='int64'),X_test]
y_train.shape
np.unique(y_test)
y1 = np.zeros([y_train.shape[0], len(np.unique(y_train))])
y1 = pd.DataFrame(y1)

In [16]:
alpha = 0.005
loops = 10000
train_predictions = fit(X_train,y_train,alpha,loops)
test_predictions = fit(X_test,y_test,alpha,loops)

In [17]:
print("train accuracy: {} %".format(100 - np.mean(np.abs(train_predictions - y_train)) * 100))
print("test accuracy: {} %".format(100 - np.mean(np.abs(test_predictions - y_test)) * 100))

train accuracy: 82.39316239316238 %
test accuracy: 78.97435897435898 %


In [18]:
from sklearn.metrics import confusion_matrix
cf_test= confusion_matrix(y_test,test_predictions)
cf_test

array([[60,  2,  0],
       [15, 42, 12],
       [ 2,  8, 54]], dtype=int64)

In [19]:
cf_train = confusion_matrix(y_train,train_predictions)
cf_train

array([[195,   3,   0],
       [ 28, 131,  32],
       [  5,  30, 161]], dtype=int64)